---

name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go:
          - 1.11.x  # debian buster
          - 1.13.x  # ubuntu focal
          - 1.x     # latest

    name: Go ${{ matrix.go }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Set up build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y -q golint

      - name: Set up GITHUB_ENV
        run: >
          go version |
          sed 's/^go version /GOVERSION=/'|
          tr ' /' '-' >>$GITHUB_ENV

      - name: Set up Go module cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ env.GOVERSION }}-module-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ env.GOVERSION }}-module-cache-

      - name: Set up Go build cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ env.GOVERSION }}-build-cache

      - name: Set up user directories
        run: xdg-user-dirs-update

      - name: Set up trash
        run: |
          mkdir -p "$HOME/.local/share/Trash/files"
          touch "$HOME/.local/share/Trash/files/file.txt"
          mkdir -p "$HOME/.local/share/Trash/info"
          printf '[Trash Info]\nPath=%s\nDeletionDate=%s\n' "$HOME/file.txt" "$(date '+%Y-%m-%dT%H:%M:%S')" >"$HOME/.local/share/Trash/info/file.txt.trashinfo"

      - run: golint github.com/rkoesters/xdg/...
      - run: go build -v github.com/rkoesters/xdg/...
      - run: go test -v -cover github.com/rkoesters/xdg/...
      - run: go vet -v github.com/rkoesters/xdg/...
